### ISSUE TITLE
Suggestion regarding mdi package and repo description

### ISSUE THREAD

**Issue by virendave96** [BootstrapDash/StarAdmin-Free-Angular-Admin-Template#6]
Hey Check this [out](https://www.npmjs.com/package/mdi)
> The mdi package was renamed to @mdi/font after v2.2.43. Please rename in your package.json for future updates.

Need changes in the following places

- [ ] package.json

- [ ] styles.css 
`@import "../node_modules/mdi/scss/materialdesignicons";`
to
`@import "../node_modules/@mdi/font/scss/materialdesignicons";`

- [ ] src\assets\styles\_variables.scss
`$mdi-font-path: "~mdi/fonts";`
to
`$mdi-font-path: "~@mdi/font/fonts";`

and change repo description replace angularjs with angular it confused me at first.

**Comment by bootstrapdash-team** [comment]
Hi @virendave96,

Thank you for the suggestions. We have modified the repository description. 

Regarding the package name of mdi, we are in a process of updating the template with bug fixes and other improvements including this. We will ge tback to you soon after the update.

**Comment by bootstrapdash-team** [comment]
Hi @virendave96 ,

We have updated mdi package as you suggested. Please have a look.
